### ISSUE TITLE
leap-mx can not parse emails

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-platform#116]
leap-mx can not parse emails anymore.
Every email that is received by wazokazi.is is put in /var/mail/vmail/Maildir and is later picked up by leap-mx.
But leap-mx fails to parse these emails and therefore no email ever reaches the recipients:
```
2015-10-05 10:23:15+0200 [HTTP11ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1155, in gotResult
	    _inlineCallbacks(r, g, deferred)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/leap/mx/mail_receiver.py", line 439, in _process_incoming_email
	    yield self._step_process_mail_backend(filepath)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/lib/python2.7/dist-packages/leap/mx/mail_receiver.py", line 416, in _step_process_mail_backend
	    do_remove = yield self._export_message(uuid, doc)
	  File "/usr/lib/python2.7/dist-packages/leap/mx/mail_receiver.py", line 250, in _export_message
	    db = CouchDatabase(self._mail_couch_url, "user-%s" % (uuid,))
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/common/couch.py", line 437, in __init__
	    self.ensure_ddocs_on_db()
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/common/couch.py", line 464, in ensure_ddocs_on_db
	    self._database.info(ddoc_name)
	exceptions.TypeError: info() takes exactly 1 argument (2 given)
```

**Comment by shyba** [comment]
https://github.com/pixelated/project-issues/issues/150 should fix it.

**Comment by shyba** [comment]
leap_mx is trying to ensure documents. It worked in the past because normally you don't have to put the design document if it is there, but now that security document is being always sent permission error is raised. There is no point in checking (ensuring as the code calls it) a design document if you can't PUT it.
I don't think leap_mx should ensure ddocs, so I will review the code and talk to leap to see where to put the fix.

**Comment by shyba** [comment]
This fix was included on PR inside https://github.com/pixelated/project-issues/issues/150

**Comment by shyba** [comment]
Deployed to unstable, my account works (received mail with no errors on mx).
Need to use our soledad-common package, but since the PR was merged I think it should work with latest leap package as well.

**Comment by pereiragislene** [comment]
I sent multiple emails to myself in Wazokazi and I received all of them.
