### ISSUE TITLE
Try pixelated dispatcher on jessie

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#131]
Investigate how much work it would be to let the dispatcher run on a jessie host.

**Comment by varac** [comment]
i started with the `0.5~137.gbpfebda4` packages from wheezy:

```
root@jessie:/etc/apt/apt.conf.d# dpkg -l pix\*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
ii  pixelated-dispatcher                      0.5~137.gbpfebda4         all                       Pixelated-dispatcher dispatches between multiple pixelated user-agents
ii  pixelated-dispatcher-common               0.5~137.gbpfebda4         all                       Pixelated-dispatcher dispatches between multiple pixelated user-agents
ii  pixelated-dispatcher-manager              0.5~137.gbpfebda4         all                       Pixelated-dispatcher dispatches between multiple pixelated user-agents
ii  pixelated-dispatcher-proxy                0.5~137.gbpfebda4         all                       Pixelated-dispatcher dispatches between multiple pixelated user-agents



root@jessie:/etc/apt/apt.conf.d# /usr/bin/pixelated-dispatcher
Traceback (most recent call last):
  File "/usr/bin/pixelated-dispatcher", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: docker-py>=0.6.0
```

i upgraded `docker-py` (was 0.5.3) using pip to the newest version (1.5.0), but after this, the service still cannot start:

```
root@jessie:~# systemctl restart pixelated-dispatcher-manager.service
root@jessie:~# systemctl status pixelated-dispatcher-manager.service -l
● pixelated-dispatcher-manager.service - LSB: Manager part of the pixelated-dispatcher
   Loaded: loaded (/etc/init.d/pixelated-dispatcher-manager)
   Active: active (exited) since Wed 2015-11-11 11:45:16 UTC; 1s ago
  Process: 2766 ExecStop=/etc/init.d/pixelated-dispatcher-manager stop (code=exited, status=0/SUCCESS)
  Process: 2777 ExecStart=/etc/init.d/pixelated-dispatcher-manager start (code=exited, status=0/SUCCESS)

Nov 11 11:45:16 local1 pixelated-dispatcher-manager[2777]: Starting pixelated-dispatcher manager: pixelated-manager.
Nov 11 11:45:16 local1 pixelated.manager[2790]: INFO Initialized logging
Nov 11 11:45:16 local1 pixelated.manager[2790]: INFO Fetching ca.crt from https://bitmask.local/ca.crt using fingerprint 33:9C:DD:57:CF:D5:B1:41:16:9B:61:5F:F3:14:28:78:2D:1D:A6:39
Nov 11 11:45:16 local1 pixelated.manager[2790]: ERROR Error while running manager: Timeout value connect was Timeout(connect=15, read=15, total=None), but it must be an int or float.
                                                Traceback (most recent call last):
                                                  File "/usr/lib/python2.7/dist-packages/pixelated/manager/__init__.py", line 280, in serve_forever
                                                    provider = self._download_api_ca_bundle()
                                                  File "/usr/lib/python2.7/dist-packages/pixelated/manager/__init__.py", line 309, in _download_api_ca_bundle
                                                    LeapCertificate(provider).refresh_api_ca_bundle()
                                                  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/leap_certs.py", line 58, in refresh_api_ca_bundle
                                                    self._download_api_ca_bundle(cert_file)
                                                  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/leap_certs.py", line 71, in _download_api_ca_bundle
                                                    cert = self._provider.fetch_valid_certificate()
                                                  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/leap_provider.py", line 76, in fetch_valid_certificate
                                                    cert = self._fetch_certificate()
                                                  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/leap_provider.py", line 86, in _fetch_certificate
                                                    response = session.get(cert_url, verify=which_bootstrap_CA_bundle(self), timeout=self.config.timeout_in_s)
                                                  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
                                                    return self.request('GET', url, **kwargs)
                                                  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
                                                    resp = self.send(prep, **send_kwargs)
                                                  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
                                                    r = adapter.send(request, **kwargs)
                                                  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 370, in send
                                                    timeout=timeout
                                                  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
                                                    body=body, headers=headers)
                                                  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 299, in _make_request
                                                    timeout_obj = self._get_timeout(timeout)
                                                  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 279, in _get_timeout
                                                    return Timeout.from_float(timeout)
                                                  File "/usr/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 152, in from_float
                                                    return Timeout(read=timeout, connect=timeout)
                                                  File "/usr/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 95, in __init__
                                                    self._connect = self._validate_timeout(connect, 'connect')
                                                  File "/usr/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 125, in _validate_timeout
                                                    "int or float." % (name, value))
                                                ValueError: Timeout value connect was Timeout(connect=15, read=15, total=None), but it must be an int or float.

```

why is there a timeout, because wgetting works:

```
root@jessie:~# wget https://bitmask.local/ca.crt -O /tmp/ca.crt
--2015-11-11 11:47:34--  https://bitmask.local/ca.crt
Resolving bitmask.local (bitmask.local)... 127.0.1.1
Connecting to bitmask.local (bitmask.local)|127.0.1.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1944 (1.9K) [application/x-x509-ca-cert]
Saving to: ‘/tmp/ca.crt’

/tmp/ca.crt                                     100%[=======================================================================================================>]   1.90K  --.-KB/s   in 0s     

2015-11-11 11:47:34 (116 MB/s) - ‘/tmp/ca.crt’ saved [1944/1944]

```

**Comment by varac** [comment]
i tried again with jessie packages, same error like above:

```
...
ValueError: Timeout value connect was Timeout(connect=15, read=15, total=None), but it must be an int or float.
```

**Comment by fbernitt** [comment]
The main problem at the moment is, that the dispatcher needs a docker-py>=0.6.0, but that is currently not available in debian jessie. But when installing it using pip, then it will also update requests and make it incompatible with the debian requests/urllib3 stuff. To fix this, we need the debian version of the package in a more current version

This are the things that are updated when docker-py is updated:
```
pip install --upgrade docker-py
Downloading/unpacking docker-py from https://pypi.python.org/packages/source/d/docker-py/docker-py-1.5.0.tar.gz#md5=fdbbd59f512384810cfd4619ac507222
  Downloading docker-py-1.5.0.tar.gz (59kB): 59kB downloaded
  Running setup.py (path:/tmp/pip-build-ZkUvgO/docker-py/setup.py) egg_info for package docker-py

Downloading/unpacking requests>=2.5.2 (from docker-py)
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB): 497kB downloaded
Downloading/unpacking six>=1.4.0 from https://pypi.python.org/packages/py2.py3/s/six/six-1.10.0-py2.py3-none-any.whl#md5=3ab558cf5d4f7a72611d59a81a315dc8 (from docker-py)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking websocket-client>=0.32.0 (from docker-py)
  Downloading websocket_client-0.34.0.tar.gz (193kB): 193kB downloaded
  Running setup.py (path:/tmp/pip-build-ZkUvgO/websocket-client/setup.py) egg_info for package websocket-client

Installing collected packages: docker-py, requests, six, websocket-client
  Found existing installation: docker-py 0.5.3
    Not uninstalling docker-py at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for docker-py

  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: six 1.8.0
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: websocket-client 0.18.0
    Not uninstalling websocket-client at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for websocket-client
    changing mode of build/scripts-2.7/wsdump.py from 644 to 755

    changing mode of /usr/local/bin/wsdump.py to 755
Successfully
```

**Comment by fbernitt** [comment]
We copied the wheezy packages to jessie. When adding theses apt sources, the dispatcher seems to work  on jessie:

```
deb http://http.debian.net/debian jessie-backports main
deb http://deb.leap.se/0.8 wheezy main

deb http://packages.pixelated-project.org/debian jessie-snapshots main
deb http://packages.pixelated-project.org/debian jessie main
```

**Comment by neissi** [comment]
we added the jessie repos and running apt-get update, and now the packages are available to install.
