### ISSUE TITLE
Wrong provider cert fingerprint in /etc/default/pixelated-dispatcher-manager

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#140]
When deploying the dispatcher to an existing leap_platform, the wrong provider cert fingerprint is configured for the pixelated-dispatcher-manager in `/etc/default/pixelated-dispatcher-manager`.
I'll add more details soon.

**Comment by varac** [comment]
this happened during the CCC multiple times and is important to fix

**Comment by varac** [comment]
i stepped into this on unstable.pix today after upgrading to jessie.
leap deploy went fine, 

```
root@unstable1:~# systemctl status pixelated-dispatcher-manager.service  -l
● pixelated-dispatcher-manager.service - LSB: Manager part of the pixelated-dispatcher
   Loaded: loaded (/etc/init.d/pixelated-dispatcher-manager)
   Active: active (exited) since Wed 2016-01-06 13:22:13 CET; 12s ago
  Process: 17938 ExecStop=/etc/init.d/pixelated-dispatcher-manager stop (code=exited, status=0/SUCCESS)
  Process: 17949 ExecStart=/etc/init.d/pixelated-dispatcher-manager start (code=exited, status=0/SUCCESS)

Jan 06 13:22:13 unstable1 pixelated-dispatcher-manager[17949]: Starting pixelated-dispatcher manager: pixelated-manager.
Jan 06 13:22:13 unstable1 pixelated.manager[17970]: INFO Initialized logging
Jan 06 13:22:13 unstable1 pixelated.manager[17970]: INFO Fetching ca.crt from https://unstable.pixelated-project.org/ca.crt using fingerprint BD:A0:27:10:D0:35:11:BB:B2:71:FD:F4:C1:75:D4:A3:89:31:5A:08
Jan 06 13:22:13 unstable1 pixelated.manager[17970]: ERROR Error while running manager: Fingerprints did not match. Expected "bda02710d03511bbb271fdf4c175d4a389315a08", got "49b4761221700f71876c147cd584901dff2be2f9".
                                                    Traceback (most recent call last):
                                                      File "/usr/lib/python2.7/dist-packages/pixelated/manager/__init__.py", line 280, in serve_forever
                                                        provider = self._download_api_ca_bundle()
                                                      File "/usr/lib/python2.7/dist-packages/pixelated/manager/__init__.py", line 309, in _download_api_ca_bundle
                                                        LeapCertificate(provider).refresh_api_ca_bundle()
                                                      File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/leap_certs.py", line 58, in refresh_api_ca_bundle
                                                        self._download_api_ca_bundle(cert_file)
                                                      File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/leap_certs.py", line 71, in _download_api_ca_bundle
                                                        cert = self._provider.fetch_valid_certificate()
                                                      File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/leap_provider.py", line 76, in fetch_valid_certificate
                                                        cert = self._fetch_certificate()
                                                      File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/leap_provider.py", line 86, in _fetch_certificate
                                                        response = session.get(cert_url, verify=which_bootstrap_CA_bundle(self), timeout=self.config.timeout_in_s)
                                                      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
                                                        return self.request('GET', url, **kwargs)
                                                      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
                                                        resp = self.send(prep, **send_kwargs)
                                                      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
                                                        r = adapter.send(request, **kwargs)
                                                      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
                                                        raise SSLError(e, request=request)
                                                    SSLError: Fingerprints did not match. Expected "bda02710d03511bbb271fdf4c175d4a389315a08", got "49b4761221700f71876c147cd584901dff2be2f9".
```


i manually put the right fingerprint into `/etc/default/pixelated-dispatcher-manager`

**Comment by cz8s** [comment]
This is the one expected:
```
root@unstable1:/usr/local/share/ca-certificates# openssl x509 -noout -fingerprint -in /etc/x509/certs/leap_commercial.crt
SHA1 Fingerprint=49:B4:76:12:21:70:0F:71:87:6C:14:7C:D5:84:90:1D:FF:2B:E2:F9
```
But this is the one we are using:
```
root@unstable1:/usr/local/share/ca-certificates# openssl x509 -noout -fingerprint -in /usr/local/share/ca-certificates/leap_commercial_ca.crt 
SHA1 Fingerprint=BD:A0:27:10:D0:35:11:BB:B2:71:FD:F4:C1:75:D4:A3:89:31:5A:08

```

We pin the fingerprint to the /etc/x509/certs/leap_commercial.crt on wazokazi. So this is the thing
we should do and which actually sounds more sane. Question now is: why does this work on
staging?

**Comment by fbernitt** [comment]
Certificate fingerprint is good now! But even though the leap deploy did not show any errors, pixelated is not running in a fresh leap platform vagrant image.

Can be launched, but not there yet...
