### ISSUE TITLE
upgrade Leap-mx on all environments

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-platform#147]
We have pinned leap-mx to version 0.7.1, from http://packages.pixelated-project.org/debian

This version of the package fails to start with the following error:

```
Starting leap_mx: twistdUnhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "/usr/share/app/mx.tac", line 87, in <module>
    to_watch = config.get(section, "path")
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'path' in section: 'fingerprint map'

Failed to load application: No option 'path' in section: 'fingerprint map'
```

**Comment by mnandri** [comment]
After investigation, we found out that the old version of leap-mx (0.7.18) that is in packages.pix does not support the fingerprint mapping that recently added (see issue https://leap.se/code/issues/4285).
We would need to upgrade to the 0.8.0 version of leap-mx to fix the issue.

We put it in blocked... awaiting for @cz8s

**Comment by cz8s** [comment]
we should already use the package from leap. See commit  
pixelated/puppet-pixelated@10d768b826880ed13438624f14b7a7412d888a15

I removed the package from packages.pixelated-project.org:
```
reprepro remove jessie-snapshots leap-mx
```

**Comment by cz8s** [comment]
@mnandri: I think our puppet does not remove files that are not used anymore. I think we will have to remove /etc/apt/preferences.d/leap-mx by hand on the envs that still have an old leap-mx

**Comment by varac** [comment]
Done: 

- [x] dev
- [ ] unstable
- [ ] wazokazi

**Comment by mnandri** [comment]
This is resolved.
leap-mx is now obtained from the official repo.
