### ISSUE TITLE
Dispatcher fails with "invalid credentials"

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#148]
Dispatcher fails with "invalid credentials".

I'll come up tomorrow with more information, but this is one of the main issues ppl experienced setting pixelated on top of a leap installation.

**Comment by re-nobre** [comment]
Hey, @varac!
When I tried to use the staging environment today I got the same error.

**Comment by varac** [comment]
This is from the logs on my local box:

```
2016-01-05T09:44:44.235246+00:00 local1 pixelated.manager: INFO User test01 logged in successfully
2016-01-05T09:44:44.243008+00:00 local1 pixelated.proxy: INFO Successful login of user test01
2016-01-05T09:44:44.243474+00:00 local1 pixelated.proxy: INFO Starting agent for test01
2016-01-05T09:44:44.773369+00:00 local1 pixelated.manager: ERROR Unhandled Error during request: 500 Server Error: Internal Server Error ("Cannot start container d3642af5b736ca6dfd3b51a152ae
6e0b7708b5aa5cd75f2fb309a51100327e49: failed to create endpoint test01 on network bridge: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0.0.0.0 --dport 5000 -j DNAT --to-destin
ation 0.0.0.0:4567 ! -i docker0: iptables: No chain/target/match by that name.#012 (exit status 1)")#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/dist-packages/pixelat
ed/manager/__init__.py", line 69, in wrapper#012    return callback(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/pixelated/manager/__init__.py", line 182, in _put_agent_state
#012    self._provider.start(user_cfg)#012  File "/usr/lib/python2.7/dist-packages/pixelated/provider/docker/__init__.py", line 275, in start#012    port_bindings={self._adapter.port(): ('0.
0.0.0', port)})#012  File "/usr/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped#012    return f(self, resource_id, *args, **kwargs)#012  File "/usr/lib/python2.7
/dist-packages/docker/api/container.py", line 343, in start#012    self._raise_for_status(res)#012  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 142, in _raise_for_status#0
12    raise errors.APIError(e, response, explanation=explanation)#012APIError: 500 Server Error: Internal Server Error ("Cannot start container d3642af5b736ca6dfd3b51a152ae6e0b7708b5aa5cd75f
2fb309a51100327e49: failed to create endpoint test01 on network bridge: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0.0.0.0 --dport 5000 -j DNAT --to-destination 0.0.0.0:4567 ! -i docker0: iptables: No chain/target/match by that name.#012 (exit status 1)")
2016-01-05T09:44:44.789525+00:00 local1 pixelated.proxy: WARNING Login attempt with invalid credentials by user test01
2016-01-05T09:44:44.791234+00:00 local1 tornado.access: INFO 302 POST /auth/login (0.0.0.0) 727.98ms
2016-01-05T09:44:44.808684+00:00 local1 tornado.access: INFO 200 GET /auth/login (0.0.0.0) 1.86ms
2016-01-05T09:44:44.983733+00:00 local1 pixelated.proxy: INFO User test01 logged out


```

**Comment by varac** [comment]
@re-nobre you're right, i get the same on staging for a newly registered user:

```
2016-01-05T10:47:40.018233+01:00 pixelated pixelated.proxy: INFO Successful login of user test11
2016-01-05T10:47:40.018436+01:00 pixelated pixelated.proxy: INFO Starting agent for test11
2016-01-05T10:47:41.854094+01:00 pixelated pixelated.manager: ERROR Unhandled Error during request: 500 Server Error: Internal Server Error ("json: cannot unmarshal number into Go value of type string")#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/dist-packages/pixelated/manager/__init__.py", line 69, in wrapper#012    return callback(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/pixelated/manager/__init__.py", line 182, in _put_agent_state#012    self._provider.start(user_cfg)#012  File "/usr/lib/python2.7/dist-packages/pixelated/provider/docker/__init__.py", line 262, in start#012    c = self._docker.create_container(self._adapter.docker_image_name(), self._adapter.run_command(self._leap_provider_x509), mem_limit=DOCKER_MEMORY_LIMIT, user=uid, name=name, volumes=['/mnt/user'], ports=[self._adapter.port()], environment=self._adapter.environment('/mnt/user'), stdin_open=True)#012  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 425, in create_container#012    return self.create_container_from_config(config, name)#012  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 433, in create_container_from_config#012    return self._result(res, True)#012  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 99, in _result#012    self._raise_for_status(response)#012  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 95, in _raise_for_status#012    raise errors.APIError(e, response, explanation=explanation)#012APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal number into Go value of type string")
2016-01-05T10:47:41.875310+01:00 pixelated pixelated.proxy: WARNING Login attempt with invalid credentials by user test11
2016-01-05T10:47:41.876693+01:00 pixelated tornado.access: INFO 302 POST /auth/login (0.0.0.0) 2231.22ms
2016-01-05T10:47:41.968698+01:00 pixelated tornado.access: INFO 200 GET /auth/login (0.0.0.0) 4.16ms
2016-01-05T10:47:42.281184+01:00 pixelated pixelated.proxy: INFO User test11 logged out


```

**Comment by varac** [comment]
ok, the problem on staging was docker in version 1.9.x, and we need 1.6.2 in order to work with the dispatcher and dockerhub. i pinned it manually on staging, and installed 1.6.2 there, amd now it works again.

**Comment by varac** [comment]
blocked by #149, we need a functional platform build first before we can deploy and try on a new staging

**Comment by varac** [comment]
works again on latest staging

**Comment by re-nobre** [comment]
I tested here and it works. 
I just needed to create again my account.
